// Edge Function — esegui migration completa (tabelle mancanti + colonne)
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const serviceKey  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase    = createClient(supabaseUrl, serviceKey);

  // Usa la service role per eseguire SQL via pg_query (Supabase internal)
  const sqlStatements = [
    // Tabella territories
    `CREATE TABLE IF NOT EXISTS public.territories (
      id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
      game_id uuid NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
      territory text NOT NULL,
      inf_iran integer NOT NULL DEFAULT 0,
      inf_coalizione integer NOT NULL DEFAULT 0,
      inf_russia integer NOT NULL DEFAULT 0,
      inf_cina integer NOT NULL DEFAULT 0,
      inf_europa integer NOT NULL DEFAULT 0,
      updated_at timestamptz DEFAULT now(),
      UNIQUE(game_id, territory)
    )`,
    // Tabella military_units
    `CREATE TABLE IF NOT EXISTS public.military_units (
      id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
      game_id uuid NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
      faction text NOT NULL,
      territory text NOT NULL,
      unit_type text NOT NULL,
      quantity integer NOT NULL DEFAULT 0,
      updated_at timestamptz DEFAULT now(),
      UNIQUE(game_id, faction, territory, unit_type)
    )`,
    // RLS territories
    `ALTER TABLE public.territories ENABLE ROW LEVEL SECURITY`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='territories' AND policyname='territories_rw')
      THEN CREATE POLICY "territories_rw" ON public.territories FOR ALL USING (true); END IF;
    END $$`,
    // RLS military_units
    `ALTER TABLE public.military_units ENABLE ROW LEVEL SECURITY`,
    `DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='military_units' AND policyname='mil_units_rw')
      THEN CREATE POLICY "mil_units_rw" ON public.military_units FOR ALL USING (true); END IF;
    END $$`,
    // game_state opzionali
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS forze_militari_iran integer NOT NULL DEFAULT 5`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS forze_militari_coalizione integer NOT NULL DEFAULT 5`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS forze_militari_russia integer NOT NULL DEFAULT 5`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS forze_militari_cina integer NOT NULL DEFAULT 5`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS forze_militari_europa integer NOT NULL DEFAULT 5`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS units_iran jsonb DEFAULT '{}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS units_coalizione jsonb DEFAULT '{}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS units_russia jsonb DEFAULT '{}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS units_cina jsonb DEFAULT '{}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS units_europa jsonb DEFAULT '{}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS special_uses jsonb DEFAULT '{"veto_russia":3,"hormuz_iran":false,"superiorita_aerea":false}'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS active_alliances jsonb DEFAULT '[]'::jsonb`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS last_event_turn integer`,
    `ALTER TABLE public.game_state ADD COLUMN IF NOT EXISTS last_event_id text`,
    // games.game_mode
    `ALTER TABLE public.games ADD COLUMN IF NOT EXISTS game_mode text NOT NULL DEFAULT 'classic'`,
    // cards_deck
    `ALTER TABLE public.cards_deck ADD COLUMN IF NOT EXISTS owner_faction text`,
    `ALTER TABLE public.cards_deck ADD COLUMN IF NOT EXISTS play_mode text`,
    // games: tavolo aperto / riservato
    `ALTER TABLE public.games ADD COLUMN IF NOT EXISTS is_public boolean NOT NULL DEFAULT false`,
    `ALTER TABLE public.games ALTER COLUMN name DROP NOT NULL`,
    `CREATE INDEX IF NOT EXISTS idx_games_public_lobby ON public.games (is_public, status) WHERE status IN ('lobby','active')`,
    // Seed cards_library — 344 carte (upsert su card_id)
    // Carte batch 1/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('C025','Arricchimento Uranio 60%','Iran','Militare','base',4,'Accelera programma nucleare',2,-1,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C026','Proxy Hezbollah','Iran','Militare','base',3,'Attivazione milizie in Libano',0,0,-1,1,-1,0,NULL,NULL,0,0,0,0,0,0),
('C027','Diplomazia Regionale','Iran','Diplomatico','base',2,'Apertura verso paesi del Golfo',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C028','Attacco Droni Houthi','Iran','Militare','base',3,'Operazioni coordinate Yemen',0,0,-1,1,-1,0,NULL,NULL,0,0,0,0,0,0),
('C029','Accordo Petrolio Cina','Iran','Economico','base',3,'Contratto ventennale Pechino',0,-1,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C030','Test Missile Balistico','Iran','Militare','base',3,'Lancio dimostrativo missili lunghi',1,0,-1,-1,-1,0,NULL,NULL,0,0,0,0,0,0),
('C031','Propaganda Press TV','Iran','Media','base',2,'Campagna mediatica internazionale',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C032','Centrifughe Avanzate','Iran','Militare','base',4,'Installazione centrifughe IR-6',3,0,-1,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('C033','Negoziato JCPOA','Iran','Diplomatico','base',3,'Ritorno tavolo dei negoziati',0,2,1,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C034','Sequestro Petroliera','Iran','Militare','base',2,'Fermo nave straniera nello Stretto',0,0,-1,-1,1,0,NULL,NULL,0,0,0,0,0,0),
('C035','Asse della Resistenza','Iran','Militare','base',3,'Coordinamento milizie regionali',0,0,-1,0,-1,1,NULL,NULL,0,0,0,0,0,0),
('C036','Cyber Difesa','Iran','Segreto','base',2,'Potenziamento sicurezza informatica',1,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('C037','Accordo SCO','Iran','Diplomatico','base',2,'Adesione Organizzazione Shanghai',0,-1,0,1,1,0,NULL,NULL,0,0,0,0,0,0),
('C038','Milizie Iraq','Iran','Militare','base',2,'Attivazione PMF in Iraq',0,0,-1,0,-1,1,NULL,NULL,0,0,0,0,0,0),
('C039','Deterrenza Nucleare','Iran','Militare','base',4,'Minaccia breakout nucleare',1,0,-1,-1,0,1,NULL,NULL,0,0,0,0,0,0),
('C040','Commercio Alternativo','Iran','Economico','base',2,'Rotte commerciali per aggirare sanzioni',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C041','Supporto Hamas','Iran','Militare','base',2,'Armi e fondi per Gaza',0,0,-1,-1,-1,0,NULL,NULL,0,0,0,0,0,0),
('C042','Diplomazia Oman','Iran','Diplomatico','base',2,'Canale segreto via Muscat',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C043','Esercitazioni Navali','Iran','Militare','base',2,'Manovre Stretto di Hormuz',0,0,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C044','Propaganda Anti-USA','Iran','Media','base',2,'Campagna Grande Satana',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C045','Sito Nucleare Segreto','Iran','Segreto','base',3,'Costruzione impianto sotterraneo',2,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('C046','Accordo Baghdad','Iran','Diplomatico','base',2,'Riavvicinamento con Arabia Saudita',0,-1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('C047','Rappresaglia Missilistica','Iran','Militare','base',3,'Attacco su basi USA nella regione',0,0,-2,0,-2,1,NULL,NULL,0,0,0,0,0,0),
('C048','Moratoria Nucleare','Iran','Diplomatico','base',2,'Sospensione temporanea arricchimento',-1,2,1,2,2,0,NULL,NULL,0,0,0,0,0,0),
('SE_I01','Centrifughe IR-9 (spec.)','Iran','Militare','speciale',4,'Centrifughe ultima generazione',3,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_I02','Sito Sotterraneo (spec.)','Iran','Segreto','speciale',3,'Bunker nucleare impenetrabile',2,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('SE_I03','Uranio 90% (spec.)','Iran','Militare','speciale',4,'Arricchimento weapon-grade',3,0,-2,0,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_I04','Accordo Sorpresa (spec.)','Iran','Diplomatico','speciale',3,'Accordo improvviso con mediatore',-1,3,0,2,2,0,NULL,NULL,0,0,0,0,0,0),
('SE_I05','Tecnologia Missilistica (spec.)','Iran','Militare','speciale',3,'Vettore intercontinentale',1,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('SE_I06','Alleanza BRICS Nucleare (spec.)','Iran','Economico','speciale',3,'Supporto blocco emergente',0,-2,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('C001','Portaerei nel Golfo','Coalizione','Militare','base',3,'Dispiegamento flotta Golfo Persico',-1,1,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C002','Sanzioni SWIFT','Coalizione','Economico','base',4,'Esclusione Iran da SWIFT',0,3,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C003','Diplomazia Shuttle','Coalizione','Diplomatico','base',2,'Missione diplomatica intensiva',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C004','Cyber Attack Stuxnet 2.0','Coalizione','Segreto','base',3,'Sabotaggio centrifughe iraniane',-2,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C005','Accordo Abraham Plus','Coalizione','Diplomatico','base',4,'Estensione accordi normalizzazione',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('C006','Strike Chirurgico','Coalizione','Militare','base',4,'Attacco mirato su impianti nucleari',-2,0,-2,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('C007','Pressione Mediatica CNN','Coalizione','Media','base',2,'Campagna mediatica contro regime',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C008','Aiuti Militari Israele','Coalizione','Militare','base',3,'Armi avanzate per Israele',0,1,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C009','Negoziato Vienna','Coalizione','Diplomatico','base',3,'Rilancio negoziati nucleari',-1,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C010','Embargo Petrolifero','Coalizione','Economico','base',3,'Blocco esportazioni petrolifere Iran',0,3,0,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('C011','Base Avanzata Qatar','Coalizione','Militare','base',2,'Potenziamento base Al Udeid',0,1,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C012','Intelligence Sharing','Coalizione','Segreto','base',2,'Condivisione intelligence alleati',-1,1,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C013','Pressione ONU','Coalizione','Diplomatico','base',2,'Risoluzione Consiglio di Sicurezza',0,2,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('C014','Difesa Missilistica THAAD','Coalizione','Militare','base',3,'Sistemi antimissile nella regione',0,1,1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C015','Operazione Freedom','Coalizione','Militare','base',4,'Operazione militare su larga scala',-2,0,-2,0,-3,0,NULL,NULL,0,0,0,0,0,0),
('C016','Sanzioni Secondarie','Coalizione','Economico','base',3,'Sanzioni chi commercia con Iran',0,2,0,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('C017','Supporto Opposizione','Coalizione','Segreto','base',2,'Finanziamento opposizione iraniana',0,1,0,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('C018','Accordo Difesa Saudita','Coalizione','Diplomatico','base',3,'Patto mutua difesa con Riyadh',0,1,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('C019','Propaganda VOA','Coalizione','Media','base',2,'Trasmissioni Voice of America farsi',0,0,0,2,0,-1,NULL,NULL,0,0,0,0,0,0),
('C020','Blocco Navale','Coalizione','Militare','base',4,'Blocco Stretto di Hormuz',0,3,-1,0,-2,0,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 2/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('C021','Congelamento Asset','Coalizione','Economico','base',2,'Blocco beni iraniani estero',0,2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C022','Summit Camp David','Coalizione','Diplomatico','base',3,'Vertice con leader regionali',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('C023','Droni Predator','Coalizione','Militare','base',2,'Sorveglianza e strike con droni',-1,0,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('C024','Rilascio Prigionieri','Coalizione','Diplomatico','base',1,'Scambio prigionieri con Iran',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_C01','Sabotaggio Fordow (spec.)','Coalizione','Segreto','speciale',4,'Distruzione sito nucleare chiave',-3,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_C02','Operazione Mossad (spec.)','Coalizione','Segreto','speciale',3,'Eliminazione scienziato nucleare',-2,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_C03','Strike F-35 (spec.)','Coalizione','Militare','speciale',4,'Raid aereo su tutti i siti',-3,0,-2,0,-3,0,NULL,NULL,0,0,0,0,0,0),
('SE_C04','Accordo Nucleare Last Minute (spec.)','Coalizione','Diplomatico','speciale',3,'Accordo storico ultimo momento',-2,3,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('SE_C05','Sanzioni Totali (spec.)','Coalizione','Economico','speciale',4,'Isolamento economico completo',0,4,0,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('SE_C06','Operazione Smantellamento (spec.)','Coalizione','Militare','speciale',4,'Operazione combinata multi-teatro',-3,1,-2,0,-3,0,NULL,NULL,0,0,0,0,0,0),
('C073R','Veto ONU Russia','Russia','Diplomatico','base',3,'Blocco risoluzioni Consiglio Sicurezza',0,-2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C074R','Vendita S-400','Russia','Militare','base',3,'Sistemi antiaerei per Iran',0,0,-1,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C075R','Belt and Road Iran','Russia','Economico','base',3,'Investimenti infrastrutturali massicci',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C076R','Esercitazioni Congiunte','Russia','Militare','base',3,'Manovre navali Golfo di Oman',0,0,-1,0,-1,1,NULL,NULL,0,0,0,0,0,0),
('C077R','Propaganda RT','Russia','Media','base',2,'Campagna mediatica anti-occidentale',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('C078R','Accordo Energia Russia-Iran','Russia','Economico','base',3,'Contratti gas e petrolio con Iran',0,-1,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('C079R','Supporto Assad','Russia','Militare','base',2,'Rafforzamento presenza in Siria',0,0,-1,0,-1,1,NULL,NULL,0,0,0,0,0,0),
('C080R','Summit SCO Russia','Russia','Diplomatico','base',2,'Vertice Organizzazione Shanghai',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C081R','Cyber Warfare Russia','Russia','Segreto','base',2,'Attacchi informatici coordinati',0,0,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('C082R','Tecnologia Nucleare Civile','Russia','Economico','base',3,'Trasferimento know-how nucleare civile',1,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C085R','Droni Shahed','Russia','Militare','base',2,'Fornitura droni a Iran',0,0,-1,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C086R','De-dollarizzazione','Russia','Economico','base',3,'Commercio in valute alternative',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C087R','Base Navale Tartus','Russia','Militare','base',2,'Espansione presenza Mediterraneo',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('C088R','Mediazione Pechino','Russia','Diplomatico','base',3,'Accordo Iran-Arabia Saudita',0,-1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C089R','Armi Avanzate Russia','Russia','Militare','base',3,'Caccia e missili per Iran',0,0,-1,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C090R','Corridoio Nord-Sud','Russia','Economico','base',2,'Rotta commerciale Russia-Iran-India',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C091R','Disinformazione','Russia','Media','base',2,'Campagna fake news anti-occidentale',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C094R','Accordo Militare Russia','Russia','Militare','base',3,'Patto cooperazione difensiva',0,0,-1,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C073C','Veto ONU Cina','Cina','Diplomatico','base',3,'Blocco risoluzioni Consiglio Sicurezza',0,-2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C075C','Belt and Road Cina','Cina','Economico','base',3,'Investimenti infrastrutturali Iran',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C078C','Accordo Energia Cina','Cina','Economico','base',3,'Contratto petrolio 25 anni',0,-3,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('C082C','Tecnologia Nucleare Cina','Cina','Economico','base',3,'Trasferimento know-how nucleare civile',1,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C083C','Crisi Taiwan','Cina','Politico','base',3,'Escalation Pacifico distrae USA',0,-1,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C086C','De-dollarizzazione Cina','Cina','Economico','base',3,'Yuan vs Dollaro',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C088C','Mediazione Diplomatica Cina','Cina','Diplomatico','base',3,'Accordo Iran-Arabia Saudita mediato da Pechino',0,-1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C090C','Porto di Chabahar','Cina','Economico','base',2,'Infrastruttura strategica in Iran',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C091C','Propaganda CGTN','Cina','Media','base',2,'Campagna mediatica anti-occidentale',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('C092C','Ferrovia Cina-Iran','Cina','Economico','base',2,'Corridoio commerciale terrestre',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C093C','Satellite Spia Cina','Cina','Segreto','base',2,'Condivisione intelligence satellitare',1,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('C094C','Accordo Militare Cina','Cina','Militare','base',3,'Patto cooperazione difensiva',0,0,-1,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C095C','Investimenti Petrolio Cina','Cina','Economico','base',2,'Sviluppo giacimenti iraniani',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C096C','Blocco Sanzioni ONU Cina','Cina','Diplomatico','base',2,'Opposizione nuove sanzioni ONU',0,-2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('C083C2','Espansione BRICS Cina','Cina','Economico','base',2,'Nuovi membri blocco economico',0,-1,0,1,1,0,NULL,NULL,0,0,0,0,0,0),
('C084C','Accordo BRICS Cina','Cina','Diplomatico','base',2,'Espansione blocco economico alternativo',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C076C','Esercitazioni Navali Cina','Cina','Militare','base',3,'Manovre nel Golfo di Oman',0,0,-1,0,-1,1,NULL,NULL,0,0,0,0,0,0),
('C087C','Rotte Commerciali Cina','Cina','Economico','base',2,'Corridoio Nord-Sud alternativo',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('C097','Mediazione UE','Europa','Diplomatico','base',3,'Proposta di pace e negoziato',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C099','INSTEX Attivo','Europa','Economico','base',2,'Meccanismo commerciale alternativo',0,-2,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('C101','Diplomazia E3','Europa','Diplomatico','base',3,'Iniziativa Francia-Germania-UK',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C102','Aiuti Umanitari UE','Europa','Economico','base',2,'Assistenza popolazione civile',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 3/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('C103','Pressione Diritti Umani','Europa','Diplomatico','base',2,'Campagna diritti in Iran',0,0,0,1,0,-1,NULL,NULL,0,0,0,0,0,0),
('C104','Accordo Gas Alternativo','Europa','Economico','base',3,'Diversificazione forniture energetiche',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C105','Rilancio JCPOA','Europa','Diplomatico','base',4,'Sforzo per salvare accordo nucleare',-1,2,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C107','Sanzioni Mirate','Europa','Economico','base',2,'Misure contro individui specifici',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C108','Dialogo Critico','Europa','Diplomatico','base',2,'Mantenimento canali diplomatici',0,0,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C109','Investimenti Ricostruzione','Europa','Economico','base',3,'Fondi per stabilizzazione regionale',0,0,0,2,1,1,NULL,NULL,0,0,0,0,0,0),
('C110','Pressione Mediatica UE','Europa','Media','base',2,'Campagna informativa equilibrata',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('C111','Accordo Turchia','Europa','Diplomatico','base',2,'Partnership strategica con Ankara',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C113','Diplomazia Energetica','Europa','Economico','base',2,'Negoziati per forniture stabili',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('C114','Conferenza di Pace','Europa','Diplomatico','base',3,'Summit multilaterale per la pace',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C116','Accordo Migranti','Europa','Diplomatico','base',2,'Gestione flussi migratori',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('C117','Tecnologia Verde','Europa','Economico','base',2,'Cooperazione energie rinnovabili',0,0,0,1,1,1,NULL,NULL,0,0,0,0,0,0),
('C119','Embargo Armi UE','Europa','Militare','base',2,'Blocco vendita armi alla regione',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('C120','Accordo Commerciale UE','Europa','Economico','base',2,'Partnership economica regionale',0,-1,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('NI01','Morte di Khamenei','Iran','Politico','base',4,'Guida Suprema deceduta 28 feb 2026',0,0,0,-1,0,-2,NULL,NULL,0,0,0,0,0,0),
('NI02','Nomina Mojtaba Khamenei','Iran','Politico','base',3,'Figlio nominato nuova Guida Suprema',0,0,0,-1,0,1,NULL,NULL,0,0,0,0,0,0),
('NI03','Chiusura Stretto di Hormuz','Iran','Militare','base',4,'Blocco totale passaggi petroliferi',0,0,-2,-2,2,0,NULL,NULL,0,0,0,0,0,0),
('NI04','Petrolio a 130 dollari','Iran','Economico','base',3,'Shock petrolifero — Iran beneficia',0,-1,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('NI05','Attivazione Houthi 28 mar','Iran','Militare','base',4,'Lancio massiccio droni Houthi',0,0,-2,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI06','Piano 15 punti Trump via Pakistan','Iran','Diplomatico','base',3,'Proposta USA recapitata via Islamabad',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI07','Risposta Iran al Piano Trump','Iran','Diplomatico','base',3,'Tehran accetta trattative preliminari',-1,2,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NI08','Bombardamento Natanz','Iran','Segreto','base',4,'Strike israeliano su impianto principale',-2,0,-1,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NI09','Negoziati di Ginevra Mar 2026','Iran','Diplomatico','base',3,'Trattativa mediata da Svizzera',0,2,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI10','Cessate il Fuoco Temporaneo','Iran','Diplomatico','base',2,'30 giorni di tregua concordata',0,0,2,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NI11','Accordo Scambio Prigionieri','Iran','Diplomatico','base',2,'150 detenuti rilasciati in cambio',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NI12','Apertura DEFCON Parziale','Iran','Diplomatico','base',2,'Ritiro parziale da soglia breakout',-1,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI13','Proposta Moratoria 3 mesi','Iran','Diplomatico','base',2,'Sospensione arricchimento breve',-1,2,1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI14','Attacco Fordow Tunnel B','Iran','Militare','base',4,'Strike su bunker alternativo',-1,0,-1,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NI15','Milizie Syria Attivate','Iran','Militare','base',3,'Attivazione proxy in Siria post-Khamenei',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI16','Marcia Funebre a Teheran','Iran','Media','base',2,'15 milioni alle esequie del Leader',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NI17','Propaganda Nuovo Regime','Iran','Media','base',2,'Campagna legittimazione Mojtaba',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NI18','Cyber Attacco su Haifa','Iran','Segreto','base',3,'Infrastrutture israeliane colpite',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI19','Rafah 2.0 - Supporto Gaza','Iran','Militare','base',3,'Rifornimento tunnel verso Gaza',0,0,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NI20','Accordo Gas Russia-Iran Mar','Iran','Economico','base',3,'Gasdotto South Pars allargato',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NI21','Moratoria Export Petrolio','Iran','Economico','base',3,'Iran sospende export per 10 giorni',0,0,-1,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NI22','Crisi Valutaria Rial','Iran','Economico','base',2,'Rial crolla del 40%',0,0,0,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NI23','Piano Ricostruzione Post-Strike','Iran','Economico','base',3,'Riparazione Natanz con aiuto Russia',1,0,0,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NI24','Accordo BRICS Mar 2026','Iran','Economico','base',2,'Incontro Brasile-Iran-Russia-Cina',0,-1,0,1,1,0,NULL,NULL,0,0,0,0,0,0),
('NI25','Missile Shabab-5 Test','Iran','Militare','base',3,'Nuovo vettore balistico a lungo raggio',1,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI26','Accordo Militare Siria','Iran','Militare','base',2,'Basi aeree condivise con Damasco',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NI27','Crisi Successione Interna','Iran','Politico','base',3,'Fazioni IRGC vs Clerici in scontro',0,0,0,-1,0,-2,NULL,NULL,0,0,0,0,0,0),
('NI28','IRGC Assume Controllo','Iran','Politico','base',3,'Forza di Qods gestisce transizione',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NI29','Petroldollari in Yuan','Iran','Economico','base',2,'Pagamenti in RMB per export oil',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NI30','Alleanza Houthi-Hezbollah Mar','Iran','Militare','base',3,'Coordinamento attacchi multipli',0,0,-2,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NI31','Disordini Interni Post-Khamenei','Iran','Politico','base',2,'Proteste nelle grandi citta',0,0,0,1,0,-2,NULL,NULL,0,0,0,0,0,0),
('NI32','Repressione IRGC','Iran','Politico','base',2,'Forze sicurezza sopprimono rivolta',0,0,0,-1,0,1,NULL,NULL,0,0,0,0,0,0),
('NI33','Accordo Oman-Mediazione','Iran','Diplomatico','base',2,'Canale backroom Muscat',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI34','Dichiarazione Soglia Zero','Iran','Militare','base',4,'Tehran dichiara deterrenza nucleare',2,0,-2,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI35','Accordo Qatar-Gas','Iran','Economico','base',2,'Fornitura aggiuntiva a Doha',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NI36','Santuario Qom Blindato','Iran','Segreto','base',2,'Impianto sotto citta santa',1,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 4/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('NI37','Drone Suicide Mar 2026','Iran','Militare','base',3,'Attacco su portaerei USS Gerald Ford',0,0,-2,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('NI38','Accordo India-Iran Mar','Iran','Economico','base',2,'Rotta Chabahar-Mumbai riattivata',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NI39','Offerta Pace con Condizioni','Iran','Diplomatico','base',3,'Iran propone JCPOA 3.0',-1,2,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NI40','Crisi Economica Sanzioni Mar','Iran','Economico','base',2,'PIL -8% primo trimestre 2026',0,-1,0,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NC01','Accordo AIEA Mar 2026','Coalizione','Diplomatico','base',3,'Ispezioni illimitate approvate',-2,2,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC02','Risoluzione ONU 2891','Coalizione','Diplomatico','base',3,'Nuove sanzioni unanime CS-ONU',0,3,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC03','IEA — Rilascio Riserve','Coalizione','Economico','base',3,'Agenzia Energetica rilascia stock',0,0,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('NC04','Proposta JCPOA 3.0','Coalizione','Diplomatico','base',4,'Nuovo accordo nucleare completo',-2,3,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NC05','Summit G7 Iran Mar 2026','Coalizione','Diplomatico','base',3,'Dichiarazione coordinata G7',0,2,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NC06','LNG Qatar verso Europa','Coalizione','Economico','base',3,'Forniture LNG extra per alleati',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NC07','Pipeline Alternativa Arabia','Coalizione','Economico','base',3,'Bypass Hormuz via terra',0,0,0,0,3,1,NULL,NULL,0,0,0,0,0,0),
('NC08','Operazione Congiunta NATO-IDF','Coalizione','Militare','base',4,'Strike coordinato NATO-Israele',-3,0,-2,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('NC09','Mandato Internazionale Mojtaba','Coalizione','Diplomatico','base',2,'Pressione legale su nuova guida',0,1,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NC10','Piano Marshall Medio Oriente','Coalizione','Economico','base',3,'100 mld ricostruzione regionale',0,0,0,2,0,2,NULL,NULL,0,0,0,0,0,0),
('NC11','Accordo Sauditi-Israele Mar','Coalizione','Diplomatico','base',3,'Normalizzazione sotto mediazione USA',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NC12','Cyber Strike su IRGC','Coalizione','Segreto','base',3,'Operazione segreta comunicazioni',0,0,-1,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NC13','Droni Reaper Mar 2026','Coalizione','Militare','base',3,'Sorveglianza avanzata siti Iran',-1,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC14','Pressione Turchia-NATO','Coalizione','Diplomatico','base',2,'Ankara chiude Bosforo a Russia',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC15','Aiuti Opposizione Iran','Coalizione','Segreto','base',2,'Finanziamento dissidenti post-Khamenei',0,0,0,1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NC16','Piano di Stabilita Iran','Coalizione','Diplomatico','base',3,'Supporto transition democratica',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NC17','Accordo Transizione Pacifica','Coalizione','Diplomatico','base',3,'USA supporta nuova leadership moderata',0,1,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NC18','Sanzioni Su Mojtaba','Coalizione','Economico','base',3,'Congelamento beni nuova guida',0,2,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC19','Operazione Bunker Buster B2','Coalizione','Militare','base',4,'Bombardamento Fordow profondi',-3,0,-2,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('NC20','Midterm USA come freno','Coalizione','Politico','base',2,'Congresso USA limita escalation',0,0,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC21','Accordo Oman-Mediazione Coal','Coalizione','Diplomatico','base',2,'Canale segreto Muscat attivo',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC22','Supporto IDF Mar 2026','Coalizione','Militare','base',3,'Munizioni intelligenti forniture',0,1,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC23','Blocco Finanziario SWIFT Plus','Coalizione','Economico','base',4,'Esclusione anche Russia da SWIFT',0,3,0,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NC24','Task Force Marina Mar 2026','Coalizione','Militare','base',3,'6 portaerei nel Golfo',0,1,-2,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC25','Pressione India-USA','Coalizione','Diplomatico','base',2,'India mantiene neutralita favorevole',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC26','AIEA Accesso Immediato','Coalizione','Diplomatico','base',2,'Ispezioni a sorpresa approvate',-1,1,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC27','Accordo Lega Araba Mar','Coalizione','Diplomatico','base',3,'22 paesi condannano Iran',0,1,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NC28','Sabotaggio Gas S. Pars','Coalizione','Segreto','base',3,'Impianto gas colpito da agenti',0,0,0,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NC29','Accordo Pakistan-USA','Coalizione','Diplomatico','base',2,'Islamabad facilita canale Iran',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC30','Risoluzione Camera USA','Coalizione','Politico','base',2,'Autorizzazione forza militare limitata',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC31','Embargo Armi Iran Rafforzato','Coalizione','Economico','base',3,'Nessuna arma entra in Iran',-1,2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC32','Operazione Psicologica Iran','Coalizione','Media','base',2,'Campagna destabilizzante interna',0,0,0,1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NC33','Accordo Bahrain-Difesa','Coalizione','Militare','base',2,'Nuova base permanente USA',0,1,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC34','Droni Acquatici nel Golfo','Coalizione','Militare','base',2,'Sorveglianza sottomarina USA',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC35','Accordo UAE Mar 2026','Coalizione','Diplomatico','base',2,'Abu Dhabi chiude porti a Iran',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NC36','Proposta Umanitaria ONU','Coalizione','Diplomatico','base',2,'Corridoio umanitario Iran proposto',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NC37','Sanzioni Precisione Energetica','Coalizione','Economico','base',3,'Blackout export OPEC Iran',0,3,0,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NC38','Intercettazione Fondi IRGC','Coalizione','Segreto','base',3,'Conti crittografati sequestrati',0,1,0,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NC39','Accordo Cipro-Basi NATO','Coalizione','Militare','base',2,'Nuove basi avanzate Mediterraneo',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NC40','Proposta Pace Definitiva','Coalizione','Diplomatico','base',4,'Road-map completa per JCPOA 3.0',-2,3,2,3,0,0,NULL,NULL,0,0,0,0,0,0),
('NR01','SPFS Alternativo SWIFT','Russia','Economico','base',3,'Sistema pagamenti russo bypass SWIFT',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR02','Veto ONU Risoluzione Iran Mar','Russia','Diplomatico','base',3,'Blocco sanzioni supplementari',0,-2,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR03','Petrolio in Rubli','Russia','Economico','base',2,'Iran paga fornitura in RUB',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR04','Accordo Gas Turchia-Russia','Russia','Economico','base',3,'TurkStream ampliato post-crisi',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR05','Veto su Missione AIEA','Russia','Diplomatico','base',2,'Blocco ispettori extra',1,-1,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NR06','Fornitura Uranio Arricchito','Russia','Economico','base',3,'Rosatom fornisce combustibile Iran',1,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 5/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('NR07','Truppe Wagner in Siria','Russia','Militare','base',3,'Rafforzamento proxy dopo Khamenei',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR08','Tecnologia S-500 a Iran','Russia','Militare','base',3,'Scudo antiaereo avanzatissimo',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR09','Piano Pace Putin Mar 2026','Russia','Diplomatico','base',3,'Proposta cessate il fuoco 6 punti',0,1,2,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR10','Summit Astana Mar 2026','Russia','Diplomatico','base',3,'Russia-Cina-Iran vertice tripartito',0,-1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR11','Offerta Mediazione Mosca','Russia','Diplomatico','base',3,'Putin propone garanzie sicurezza',0,1,2,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR12','Corridoio Umanitario Russia','Russia','Diplomatico','base',2,'Proposta passaggio civili Iran',0,0,1,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NR13','Esercitazioni Russia-Cina-Iran','Russia','Militare','base',4,'Manovre congiunte nel Caspio',0,0,-2,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR14','Disinformazione Post-Khamenei','Russia','Media','base',2,'Fake news su successione interna',0,0,0,2,0,-1,NULL,NULL,0,0,0,0,0,0),
('NR15','Pipeline Kashagan Russia','Russia','Economico','base',2,'Rotta petrolio Kazakhstan-Russia',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR16','Commercio Iran-Russia Mar','Russia','Economico','base',3,'Scambio beni sotto sanzioni',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR17','Difesa Cosmica Russa','Russia','Segreto','base',2,'Satellite anti-drone per Iran',1,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR18','Minaccia Escalation Nucleare','Russia','Militare','base',3,'Messaggi strategici a NATO',0,0,-2,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR19','Accordo Mar Caspio Russia','Russia','Diplomatico','base',2,'Regime legale rinnovato',0,0,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('NR20','Cyberattacco Congiunto','Russia','Segreto','base',2,'Operazione disinformazione',0,0,0,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NR21','Garanzie Sicurezza Mosca','Russia','Diplomatico','base',3,'Russia offre ombrello non ufficiale',1,0,1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR22','Blocco Ormuz Russia','Russia','Militare','base',3,'Truppe navali fiancheggiano Iran',0,0,-1,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NR23','Accordo Cereali-Iran','Russia','Economico','base',2,'Wheat swap contro petrolio',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR24','Propaganda Multilingua','Russia','Media','base',2,'Campagna in arabo-farsi-inglese',0,0,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NR25','Base Navale Bandar Abbas','Russia','Militare','base',3,'Russia usa porto iraniano',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR26','Fornitura Missili Ipersonici','Russia','Militare','base',3,'Zircon forniti a Iran',0,0,-2,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR27','Isolamento Diplomatico USA','Russia','Diplomatico','base',2,'Campagna ONU contro unilateralismo',0,-1,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NR28','Accordo SCO Allargato Mar','Russia','Diplomatico','base',2,'Nuovi membri pro-Iran ammessi',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR29','Energia Nucleare Rosatom','Russia','Economico','base',3,'Seconda centrale Bushehr',1,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR30','Offerta Armenia come Buffer','Russia','Diplomatico','base',2,'Zona neutra proposta',0,0,1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR31','Accordo Drone Shahed 3.0','Russia','Militare','base',3,'Nuova gen droni prodotta in Iran',0,0,-1,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NR32','Rete Bancaria Alternativa','Russia','Economico','base',2,'Sistema interbancario BRICS+',0,-2,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NR33','Operazione Speciale Siria Mar','Russia','Militare','base',2,'Basi russe rafforzate',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR34','Piano Reintegro Iran in SCO','Russia','Diplomatico','base',2,'Iran membro pieno con garanzie',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR35','Difesa Anti-Drone Regionale','Russia','Militare','base',3,'Sistema integrato Russia-Iran-Siria',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NR36','Accordo Energetico Storico Mar','Russia','Economico','base',4,'Mega-contratto 40 anni gas/oil',0,-2,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('NR37','Cerimonia SCO Allargata','Russia','Diplomatico','base',2,'Summit con 15 paesi in presenza',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NR38','Assistenza Tecnica Nucleare','Russia','Segreto','base',3,'Tecnici Rosatom a Natanz',1,0,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NR39','Propaganda RT Arabia Saudita','Russia','Media','base',2,'Indebolimento alleanza Riyadh-USA',0,0,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NR40','Piano Pace Proposta All-In','Russia','Diplomatico','base',4,'Road-map completa Russia per Iran',-1,2,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NN01','Accordo Petrolio RMB Mar 2026','Cina','Economico','base',3,'Pagamenti in Yuan per oil iraniano',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN02','Veto Cina-Russia Congiunto','Cina','Diplomatico','base',3,'Doppio veto su risoluzione Iran',0,-2,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN03','Piano 25 anni Upgrade','Cina','Economico','base',3,'Revisione accordo bilaterale',0,-2,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('NN04','Yuan come Riserva Regionale','Cina','Economico','base',3,'Paesi Golfo adottano RMB',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN05','BRICS Development Bank Iran','Cina','Economico','base',2,'Prestito 20 mld a Tehran',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN06','Blocco Sanzioni Cina ONU','Cina','Diplomatico','base',2,'Veto a nuove misure restrittive',0,-2,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NN07','Ferrovia Speed Rail Cina-Iran','Cina','Economico','base',3,'Ferrovia rapida Isfahan-Tehran',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NN08','Propaganda Xinhua Mar 2026','Cina','Media','base',2,'Narrazione positiva su Iran',0,0,0,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NN09','Piano Pace Xi Mar 2026','Cina','Diplomatico','base',4,'Proposta 12 punti per disarmo',-1,2,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NN10','Accordo Trilaterale Cina-Iran-Pak','Cina','Diplomatico','base',3,'Corridoio strategico sigillato',0,-1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN11','Operazione Cyber Contro USA','Cina','Segreto','base',3,'Attacchi coordinati su infrastrutture',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NN12','Accordo Con Arabia Saudita','Cina','Diplomatico','base',3,'Estensione mediazione 2023',0,-1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN13','Proposta Cessate il Fuoco Mar','Cina','Diplomatico','base',3,'Pechino chiede pausa 90 giorni',-1,0,2,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN14','Accordo Mar 2026 con Qatar','Cina','Economico','base',2,'Fornitura LNG quindicennale',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN15','Accordo Chabahar Port 2.0','Cina','Economico','base',3,'Espansione porto strategico',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NN16','Mediazione Iran-Arabia Saudita 2','Cina','Diplomatico','base',3,'Seconda mediazione Cina per pace',0,-1,1,2,0,0,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 6/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('NN17','Pattuglia Navale Golfo Cina','Cina','Militare','base',3,'Presenza navale PLA nel Golfo',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NN18','Accordo con Iraq Mar 2026','Cina','Economico','base',2,'Raffinerie cinesi in Iraq',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN19','Fornitura Radar Cinesi','Cina','Militare','base',2,'Sistema difesa aerea per Iran',0,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NN20','Summit ASEAN + Iran','Cina','Diplomatico','base',2,'Iran invitato come osservatore',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN21','Accordo Tecnologico Huawei-Iran','Cina','Economico','base',3,'Rete 5G per Iran',0,0,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('NN22','De-dollarizzazione Accelerata','Cina','Economico','base',3,'Cina coordina 30 paesi anti-dollaro',0,-2,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN23','Accordo Spaziale Cina-Iran','Cina','Segreto','base',2,'Satelliti spia condivisi',1,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NN24','Progetto BRI Energia','Cina','Economico','base',3,'Pipeline Sud Pars - Cina',0,-1,0,0,3,0,NULL,NULL,0,0,0,0,0,0),
('NN25','Accordo Agricoltura Iran-Cina','Cina','Economico','base',2,'Grano cinese per uranio raw',0,-1,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN26','Visita Xi a Tehran Mar 2026','Cina','Diplomatico','base',3,'Prima visita in 10 anni',0,-1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NN27','Accordo Moneta Digitale','Cina','Economico','base',2,'CBDC cinese in Iran',0,-1,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NN28','Summit SCO Cina Mar 2026','Cina','Diplomatico','base',2,'Riunione plenaria ampliata',0,-1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NN29','Portacontainer Stretto Hormuz','Cina','Militare','base',3,'Scorta navale PLA a flotta cargo',0,0,-1,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NN30','Finanziamento Catena Droni','Cina','Militare','base',2,'Componentistica per Shahed',0,0,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NN31','Accordo Militare Trilaterale','Cina','Militare','base',3,'Patto difesa con Iran e Russia',0,0,-1,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NN32','Investimenti Porto Hormuz','Cina','Economico','base',2,'Terminal cinese a Bandar Abbas',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NN33','Fornitura Sistemi EW Cina','Cina','Militare','base',2,'Guerra elettronica per Iran',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NN34','Veto Cina su Sanzioni Gas','Cina','Diplomatico','base',2,'Blocco misure su Sh. Pars',0,-1,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NN35','Proposta Roadmap Energia','Cina','Economico','base',3,'Piano energetico 2026-2036',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NN36','Accordo Mar Caspio Cina','Cina','Diplomatico','base',2,'Presenza navale nel Caspio',0,0,0,0,0,1,NULL,NULL,0,0,0,0,0,0),
('NN37','Cyberattacco su AIEA','Cina','Segreto','base',3,'Dati ispettori AIEA compromessi',1,0,0,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NN38','Piano Umanitario Cina','Cina','Diplomatico','base',2,'Aiuti civili post-bombardamenti',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NN39','Accordo Ferrovia Kurdistan-Cina','Cina','Economico','base',2,'Rotta alternativa bypass Iran',0,0,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NN40','Accordo Storico Cina-Iran-Russia','Cina','Diplomatico','base',4,'Trattato trilaterale mutua difesa',1,-2,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE01','JCPOA 3.0 Proposta UE','Europa','Diplomatico','base',4,'Piano comprensivo accordo nucleare',-2,3,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE02','Missione Borrell Mar 2026','Europa','Diplomatico','base',3,'Visita diplomatica ad alto livello Tehran',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE03','Corridoio Energetico UE','Europa','Economico','base',3,'Diversificazione LNG post-crisi',0,0,0,0,2,2,NULL,NULL,0,0,0,0,0,0),
('NE04','Accordo AIEA-UE Mar 2026','Europa','Diplomatico','base',3,'Monitoraggio rinforzato siti nucleari',-1,1,1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NE05','Missione Macron a Tehran','Europa','Diplomatico','base',3,'Proposta pace personale Macron',0,1,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE06','Accordo Scholz-Iran Canale','Europa','Diplomatico','base',2,'Canale Berlino-Tehran riaperto',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE07','Piano Pace E3 Mar 2026','Europa','Diplomatico','base',4,'Road-map Francia-UK-Germania',-1,2,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE08','Conferenza Vienna Bis','Europa','Diplomatico','base',3,'Rilancio negoziati nucleari Vienna',-1,2,2,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE09','Mediazione Svizzera UE','Europa','Diplomatico','base',2,'Canale neutro riattivato',0,1,2,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE10','Crisi Energetica Europa Mar','Europa','Economico','base',3,'Gas a 350 EUR/MWh — misure emergenza',0,0,0,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NE11','Piano Energie Rinnovabili UE','Europa','Economico','base',3,'Accelerazione solare per indipendenza',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NE12','Accordo Qatar LNG Mar 2026','Europa','Economico','base',3,'Contratto emergenza fornitura gas',0,0,0,0,3,1,NULL,NULL,0,0,0,0,0,0),
('NE13','Solidarieta UE Post-Strike','Europa','Economico','base',2,'Piano aiuti per popolazioni colpite',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NE14','Missione Umanitaria UN-UE','Europa','Diplomatico','base',2,'ONU+UE corridoi aiuti Iran',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NE15','Aiuti Civili Post-Bombardamento','Europa','Economico','base',2,'50 mln euro per civili iraniani',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NE16','Risoluzione Parlamento Europeo','Europa','Politico','base',2,'Appello per soluzione diplomatica',0,0,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE17','Sanzioni Mirate UE su IRGC','Europa','Economico','base',3,'Congelamento asset comandanti IRGC',0,2,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE18','Pressione su Russia — Gas UE','Europa','Economico','base',3,'Blocco pagamenti gas russo',0,1,0,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NE19','Accordo Israele-UE Mar 2026','Europa','Diplomatico','base',2,'Sostegno reciproco post-strike',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE20','Crisi Rifugiati Iran-Turchia','Europa','Diplomatico','base',2,'750.000 profughi verso Europa',0,0,0,-1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NE21','Piano Stabilizzazione Regionale','Europa','Economico','base',3,'Fondi UE per ricostruzione M.O.',0,0,0,2,0,2,NULL,NULL,0,0,0,0,0,0),
('NE22','Accordo Giordania-UE','Europa','Diplomatico','base',2,'Partner chiave per gestione crisi',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NE23','Embargo Gas Russo UE','Europa','Economico','base',3,'Stop import gas russo post-crisi',0,1,0,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('NE24','Accordo Azerbaigian-UE Gas','Europa','Economico','base',3,'Pipeline del Caspio massimizzata',0,0,0,0,2,1,NULL,NULL,0,0,0,0,0,0),
('NE25','Fondo Emergenza UE 100mld','Europa','Economico','base',3,'Mobilitazione straordinaria Consiglio',0,0,0,0,1,2,NULL,NULL,0,0,0,0,0,0),
('NE26','Pressione Diplomatica su Cina','Europa','Diplomatico','base',2,'UE chiede stop forniture Iran',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Carte batch 7/7
    `INSERT INTO public.cards_library(card_id,card_name,faction,card_type,deck_type,op_points,description,delta_nucleare,delta_sanzioni,delta_defcon,delta_opinione,delta_risorse,delta_stabilita,linked_card_id,linked_description,linked_delta_nucleare,linked_delta_sanzioni,linked_delta_defcon,linked_delta_opinione,linked_delta_risorse,linked_delta_stabilita) VALUES
('NE27','Accordo Turchia-UE Transito','Europa','Diplomatico','base',2,'Transito aiuti via Ankara',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NE28','Mediazione Alto Rapp. UE','Europa','Diplomatico','base',3,'Proposta strutturata per tregua',0,1,2,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE29','Rilancio INSTEX Mar 2026','Europa','Economico','base',2,'Meccanismo pagamenti umanitari',0,-1,0,0,1,0,NULL,NULL,0,0,0,0,0,0),
('NE30','Piano Crisi Energetica 2026','Europa','Economico','base',3,'Tetto prezzi gas e misure strutturali',0,0,0,0,1,2,NULL,NULL,0,0,0,0,0,0),
('NE31','Proposta Conferenza Sicurezza','Europa','Diplomatico','base',3,'Summit internazionale Medio Oriente',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NE32','Dichiarazione G7 Energia','Europa','Politico','base',2,'Coordinamento prezzi e forniture',0,0,0,0,1,1,NULL,NULL,0,0,0,0,0,0),
('NE33','Accordo Libia-UE Energia','Europa','Economico','base',2,'Gas libico per emergenza',0,0,0,0,2,0,NULL,NULL,0,0,0,0,0,0),
('NE34','Embargo Armi UE Rafforzato','Europa','Militare','base',2,'Stop forniture a tutte le parti',0,1,0,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE35','Piano Ricostruzione Post-Guerra','Europa','Economico','base',4,'250 mld per Medio Oriente',0,0,0,3,1,2,NULL,NULL,0,0,0,0,0,0),
('NE36','Accordo Grecia-Cipro Basi','Europa','Militare','base',2,'Espansione base navale',0,0,-1,0,0,0,NULL,NULL,0,0,0,0,0,0),
('NE37','Missione EUFOR Iran','Europa','Militare','base',3,'Forza europea per corridoio sicuro',0,0,1,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NE38','Accordo Egitto-UE Mediazione','Europa','Diplomatico','base',2,'Cairo come facilitatore',0,0,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NE39','Fondo Umanitario ECHO','Europa','Economico','base',2,'Aiuti rapidi per civili',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NE40','Soluzione Diplomatica Definitiva','Europa','Diplomatico','base',4,'Accordo completo mediato UE',-2,3,3,3,0,0,NULL,NULL,0,0,0,0,0,0),
('NT01','Notizie Morte Khamenei','Neutrale','Evento','base',1,'Shock geopolitico mondiale',0,0,-1,-1,0,-2,NULL,NULL,0,0,0,0,0,0),
('NT02','Petrolio 130$ shock','Neutrale','Evento','base',1,'Crisi energetica mondiale',0,0,0,-1,-2,-2,NULL,NULL,0,0,0,0,0,0),
('NT03','ONU Sessione Emergenza','Neutrale','Diplomatico','base',2,'Sessione speciale CdS',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NT04','Crisi Stretto di Hormuz','Neutrale','Evento','base',1,'Blocco 30% flusso oil mondiale',0,0,-1,0,-3,-2,NULL,NULL,0,0,0,0,0,0),
('NT05','Drone Houthi Supertanker','Neutrale','Militare','base',2,'Attacco su petrochimico saudita',0,0,-1,0,-1,-1,NULL,NULL,0,0,0,0,0,0),
('NT06','Piano Trump 15 Punti','Neutrale','Diplomatico','base',3,'Proposta USA mediata via Pakistan',0,2,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NT07','Mercati Finanziari Panico','Neutrale','Economico','base',1,'Crollo borse mondiali -18%',0,0,0,0,-2,-2,NULL,NULL,0,0,0,0,0,0),
('NT08','Emergenza Nucleare AIEA','Neutrale','Evento','base',1,'Alert massimo rilevatori iraniani',2,0,-2,0,0,-1,NULL,NULL,0,0,0,0,0,0),
('NT09','Cessate il Fuoco Unilaterale','Neutrale','Diplomatico','base',2,'Tregua autoimpostasi',0,0,2,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NT10','Crisi Profughi Regionale','Neutrale','Evento','base',1,'2 milioni sfollati in 3 giorni',0,0,0,-1,0,-2,NULL,NULL,0,0,0,0,0,0),
('NT11','Summit ONU Emergenza Mar 2026','Neutrale','Diplomatico','base',2,'Sessione plenaria AG-ONU',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NT12','Pirateria Golfo di Aden','Neutrale','Militare','base',1,'Aumento attacchi post-crisi',0,0,-1,0,-1,0,NULL,NULL,0,0,0,0,0,0),
('NT13','Blocco Canale di Suez','Neutrale','Evento','base',1,'Mina navale blocca traffico',0,0,-1,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NT14','Dimissioni Governo Kuwait','Neutrale','Politico','base',1,'Instabilita regionale a cascata',0,0,0,-1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NT15','Accordo Qatar Mediazione','Neutrale','Diplomatico','base',2,'Doha ospita colloqui segreti',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NT16','Crollo Rial Iraniano','Neutrale','Economico','base',1,'Moneta perde 50% valore',0,-1,0,0,-2,-2,NULL,NULL,0,0,0,0,0,0),
('NT17','Attacco Cyber su Pipeline Saudita','Neutrale','Segreto','base',2,'Aramco colpita — attribuzione incerta',0,0,-1,0,-2,0,NULL,NULL,0,0,0,0,0,0),
('NT18','Proposta Peace Nobel Committee','Neutrale','Diplomatico','base',1,'Premio Nobel per Pace ai mediatori',0,0,0,3,0,1,NULL,NULL,0,0,0,0,0,0),
('NT19','Terremoto Politico in Israele','Neutrale','Politico','base',1,'Caduta governo durante crisi',0,0,1,-1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NT20','ONU — Risoluzione 2892','Neutrale','Diplomatico','base',2,'Appello alla pace unanime',0,1,1,2,0,0,NULL,NULL,0,0,0,0,0,0),
('NT21','Crisi Shipping Globale','Neutrale','Economico','base',1,'Rotte marittime +300% costo',0,0,0,0,-2,-1,NULL,NULL,0,0,0,0,0,0),
('NT22','Tweet Trump su Iran','Neutrale','Media','base',1,'Messaggio presidenziale volatile',0,0,-1,-1,0,-1,NULL,NULL,0,0,0,0,0,0),
('NT23','Accordo India-Pakistan Neutralita','Neutrale','Diplomatico','base',2,'Entrambi dichiarano non coinvolgimento',0,0,1,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NT24','Turchia — Mediazione Attiva','Neutrale','Diplomatico','base',2,'Erdogan propone vertice Istanbul',0,1,1,1,0,0,NULL,NULL,0,0,0,0,0,0),
('NT25','Crisi Liquidity Banche Regionali','Neutrale','Economico','base',1,'FMI interviene con liquidita emergenza',0,0,0,0,-1,-1,NULL,NULL,0,0,0,0,0,0),
('NT26','Discorso Mojtaba alla Nazione','Neutrale','Politico','base',1,'Prima allocuzione pubblica nuova Guida',0,0,0,1,0,1,NULL,NULL,0,0,0,0,0,0),
('NT27','Accordo di Evacuazione Civili','Neutrale','Diplomatico','base',2,'CICR facilita corridoi sicuri',0,0,0,2,0,1,NULL,NULL,0,0,0,0,0,0),
('NT28','Report AIEA Mar 2026','Neutrale','Diplomatico','base',2,'Documento ufficiale avanzamento Iran',2,1,0,-1,0,0,NULL,NULL,0,0,0,0,0,0),
('NT29','Crisi Alimentare Medio Oriente','Neutrale','Evento','base',1,'Blocco forniture grano da Mar Nero',0,0,0,-2,-1,-2,NULL,NULL,0,0,0,0,0,0),
('NT30','Segnali Pace Regionale','Neutrale','Diplomatico','base',3,'Segnali positivi da tutte le parti',0,2,2,2,0,2,NULL,NULL,0,0,0,0,0,0)
ON CONFLICT (card_id) DO UPDATE SET card_name=EXCLUDED.card_name,faction=EXCLUDED.faction,card_type=EXCLUDED.card_type,deck_type=EXCLUDED.deck_type,op_points=EXCLUDED.op_points,description=EXCLUDED.description,delta_nucleare=EXCLUDED.delta_nucleare,delta_sanzioni=EXCLUDED.delta_sanzioni,delta_defcon=EXCLUDED.delta_defcon,delta_opinione=EXCLUDED.delta_opinione,delta_risorse=EXCLUDED.delta_risorse,delta_stabilita=EXCLUDED.delta_stabilita,updated_at=NOW()`,
    // Reload schema cache
    `NOTIFY pgrst, 'reload schema'`,
  ];

  const results: { sql: string; ok: boolean; error?: string }[] = [];

  for (const sql of sqlStatements) {
    try {
      // Usa fetch diretto alla REST API interna con service key (bypassa RLS)
      const res = await fetch(`${supabaseUrl}/rest/v1/rpc/run_sql`, {
        method: 'POST',
        headers: {
          'apikey': serviceKey,
          'Authorization': `Bearer ${serviceKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: sql }),
      });
      const body = await res.json();
      if (body.error || (body.code && body.code !== '00000')) {
        results.push({ sql: sql.slice(0, 80).replace(/\s+/g, ' '), ok: false, error: body.message ?? JSON.stringify(body) });
      } else {
        results.push({ sql: sql.slice(0, 80).replace(/\s+/g, ' '), ok: true });
      }
    } catch (e: unknown) {
      results.push({ sql: sql.slice(0, 80).replace(/\s+/g, ' '), ok: false, error: String(e) });
    }
  }

  const allOk = results.every(r => r.ok);
  return new Response(JSON.stringify({ allOk, results }), {
    status: allOk ? 200 : 207,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
});
